#!/usr/bin/env bash

FILE=$(fd --type f --hidden --exclude .git | fzf --reverse \
  --preview 'bat --color=always --style=numbers --line-range=:500 {}' \
  --preview-window=right:60%)

[ -n "$FILE" ] && ${EDITOR:-nvim} "$FILE"
