set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on
setw -g mode-keys vi
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g escape-time 0
set -g focus-events on
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:Tc"

set -g status-bg default
set -g status-style bg=default
set -g status-right ""
set -g status-left-length 50
set -g status-right-length 0

# custom status bar theme
set -g status on
set -g status-position bottom
set -g status-interval 2
set -g status-justify centre
set -g status-style "bg=default,fg=#9aa4b2"
set -g status-left-length 36
set -g status-right-length 80

set -g status-left "#[fg=#0f1115,bg=#4f7c82,bold] #S #[fg=#4f7c82,bg=#0f1115] "

set -g status-right "#[fg=#7f8794,bg=#0f1115] %a %d %b #[fg=#e5c07b,bg=#0f1115,bold] %H:%M "

setw -g window-status-separator " "

setw -g window-status-format "#[fg=#cf8f92,bg=#0f1115]#[fg=#0f1115,bg=#cf8f92] #I:#W #[fg=#cf8f92,bg=#0f1115]"

setw -g window-status-current-format "#[fg=#a56d70,bg=#0f1115]#[fg=#0f1115,bg=#a56d70,bold] #I:#W #[fg=#a56d70,bg=#0f1115]"

setw -g window-status-bell-style "fg=#0f1115,bg=#e06c75,bold"
set -g message-style "bg=#1a1d24,fg=#d3dae3"
set -g message-command-style "bg=#1a1d24,fg=#e5c07b"
bind -n M-Left  resize-pane -L 5
bind -n M-Right resize-pane -R 5
bind -n M-Up    resize-pane -U 5
bind -n M-Down  resize-pane -D 5

setw -g aggressive-resize on

set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setqc=\E[58:2::%p1%{65536}%/%d:%p1%{256}%/%{255}%&%d:%p1%{255}%&%d%;m'

bind-key a last-window
unbind c
bind c new-window -c "#{pane_current_path}"

bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"

unbind %
unbind '"'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
